### ISSUE TITLE
Support sqlite3

### ISSUE THREAD

**Issue by Riduidel** [gandazgul/Mandolin#1]
Mandolin currently uses sqlite 2 library, it seems ...
It would be nice to use sqlite3 (which, incidentally, is available on my NAS, as opposed to sqlite 2).
I will work on that feature ... soon.

**Comment by gandazgul** [comment]
Thanks for you comment.

I use PDO with sqlite: DSN which should support sqlite3 depending on the version of PHP. I havent really updated this project in years so I'm not sure how is working this days. I've been using plex and spotify.

**Comment by Riduidel** [comment]
It appears Plex and spotify don't work when you're in a company network 
with a filtering proxy :-)

Anyway, SQLite may work, but the install wizard requires the 
"sqlite_query" function to be present.
And, as my NAS (which hosts Mandolin and my MP3 library) has a PHP 
compiled with sqlite3, but no sqlite support, I'll have to change all 
Mandolin code to use the sqlite3.so library (which may not be easy 
considering I'm not a PHP developer)

**Comment by gandazgul** [comment]
Ah, that sounds like an easy fix, I can change that line on the install, I think is meant to check if you have SQLite enabled, not check for a particular version.

**Comment by gandazgul** [comment]
Ok, I committed a fix, I'm using extension_loaded('pdo_sqlite') instead of checking for that particular function.

Please let me know if it works for you. And let me know if you have any other problems using Mandolin.
